apiVersion: v2
name: postgresql
description: HA PostgreSQL cluster managed by Patroni
type: application
version: 0.2.0
appVersion: 11.5.0
home: https://www.postgresql.org
icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
keywords:
  - postgresql
  - patroni
  - database
  - sql
sources:
  - https://github.com/acoustid/k8s-postgresql
  - https://github.com/postgres/postgres
  - https://github.com/zalando/patroni
maintainers:
  - name: lalinsky
    email: lalinsky@gmail.com
